feat: add full privacy signature
Arianee/conventions pull request #222
Opened 2024-08-01 09:18 UTC by gnarco

2024-08-01 13:08 UTC, alexishecf approved these changes

2024-08-01 14:23 UTC, stefdelec requested changes

2024-08-01 14:23 UTC, stefdelec commented on public/version7/ArianeeProductCertificate-i18n.json
> +  "$id": "https://cert.arianee.org/version6/ArianeeProductCertificate-i18n.json",
version7

2024-08-01 14:39 UTC, gnarco commented on public/version7/ArianeeProductCertificate-i18n.json
> +  "$id": "https://cert.arianee.org/version6/ArianeeProductCertificate-i18n.json",
fixed

2024-08-01 20:49 UTC, stefdelec requested changes

2024-08-01 20:49 UTC, stefdelec commented on public/version2/ArianeeMessage-i18n.json
> +    "$id": "https://cert.arianee.org/version1/ArianeeMessage-i18n.json",
version2

2024-08-01 20:49 UTC, stefdelec commented on public/version2/ArianeeEvent-i18n.json
> +  "$id": "https://cert.arianee.org/version1/ArianeeEvent-i18n.json",
version2

2024-08-02 07:45 UTC, stefdelec approved these changes

2024-08-07 07:30 UTC, stefdelec approved these changes

2024-08-07 07:30 UTC, merged